### ISSUE TITLE
Searching in SFTP

### ISSUE THREAD

**Issue by eugesd** [liximomo/vscode-remote-fs#39] opened 2018-10-09 19:45 UTC
Hi,

I'm trying to search through all my files in my remote directory but I came across this when trying to search
`
No search provider registered for scheme: sftp`

Any tips?

Thanks,
Eugenio

**Comment by liximomo** [comment] 2018-10-10 01:55
Duplicate of #2

**Closed by liximomo** 2018-10-10 01:55 UTC
